# Generated by Django 5.0.7 on 2025-07-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seithi', '0009_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
    ]
