# Generated by Django 5.0.7 on 2025-08-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seithi', '0010_alter_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='istop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
