# Generated by Django 5.0.7 on 2025-08-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seithi', '0012_magazine_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='repoter',
            field=models.ManyToManyField(blank=True, to='seithi.repoter'),
        ),
    ]
