# Generated by Django 5.0.7 on 2025-08-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seithi', '0013_repoter_news_repoter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='istop',
        ),
    ]
